server:
  port: 8082

spring:
  dubbo:
    application:
      name: dubbo-consumer
    registry:
      address: zookeeper://127.0.0.1:2181
    procotol:
      name: dubbo
    consumer:
      check: false
    reference:
      loadbalance: roundrobin




